apiStyle = "HuggingFace" #API style, could be "HuggingFace" or "Linseer"
configVersion = 2 #Configuration version, don't change this
statistics = "http://10.113.36.121/kong/RdTestResourceStatistic"
#userId = "" #Uncomment to use custom userId instead of windows user directory name

[[modelConfigs]]
modelType = "ComwareV1"

[modelConfigs.completionConfigs.function]
contextLimit = 1_500
endpoint = "http://10.113.36.104"
maxTokenCount = 512
stopTokens = ["<fim_pad>", "<|endoftext|>", "\n}"]
suggestionCount = 1
temperature = 0.2

[modelConfigs.completionConfigs.line]
contextLimit = 1_500
endpoint = "http://10.113.36.104:81"
maxTokenCount = 48
stopTokens = ["<fim_pad>", "<|endoftext|>", "\n}"]
suggestionCount = 1
temperature = 0.2

[modelConfigs.completionConfigs.snippet]
contextLimit = 1_500
endpoint = "http://10.113.36.104"
maxTokenCount = 128
stopTokens = ["<fim_pad>", "<|endoftext|>", "\n}"]
suggestionCount = 1
temperature = 0.2

[modelConfigs.separateTokens]
end = "<fim_suffix>"
middle = "<fim_middle>"
start = "<fim_prefix>"

[[modelConfigs]]
modelType = "ComwareV2"

[modelConfigs.completionConfigs.function]
contextLimit = 1_500
endpoint = "http://10.113.36.111"
maxTokenCount = 512
stopTokens = ["<fim_pad>", "<|endoftext|>", "</s>", "\n}"]
suggestionCount = 1
temperature = 0.2

[modelConfigs.completionConfigs.line]
contextLimit = 1_500
endpoint = "http://10.113.36.111"
maxTokenCount = 48
stopTokens = ["<fim_pad>", "<|endoftext|>", "</s>", "\n}"]
suggestionCount = 1
temperature = 0.2

[modelConfigs.completionConfigs.snippet]
contextLimit = 1_500
endpoint = "http://10.113.36.111"
maxTokenCount = 128
stopTokens = ["<fim_pad>", "<|endoftext|>", "</s>", "\n}"]
suggestionCount = 1
temperature = 0.2

[modelConfigs.separateTokens]
end = "_<SUF>"
middle = "_<MID>"
start = "_<PRE>"

[server]
host = "localhost"
port = 3_000
