apiType = "Linseer"
authRequired = true
statistics = "http://rdee.h3c.com/kong/RdTestResourceStatistic"
#userId = "" #Uncomment to use custom userId instead of user directory name

[[modelConfigs]]
contextLimit = 1_500
endpoint = "http://rdee.h3c.com/kong/RdTestAiService/chatgpt"
modelType = "Linseer"
stopTokens = [ "<fim_pad>", "<|endoftext|>", "</s>", "\n}" ]
suggestionCount = 1
temperature = 0.2

[modelConfigs.maxNewTokens]
function = 512
line = 48
snippet = 128

[[modelConfigs]]
contextLimit = 1_500
endpoint = "http://rdee.h3c.com/kong/RdTestAiService/chatgpt"
modelType = "Linseer-SR88Driver"
stopTokens = [ "<fim_pad>", "<|endoftext|>", "</s>", "\n}" ]
suggestionCount = 1
temperature = 0.2

[modelConfigs.maxNewTokens]
function = 512
line = 48
snippet = 128

[server]
host = "localhost"
port = 3000
