apiType = "HuggingFace"
authRequired = true
statistics = "http://10.113.36.121/kong/RdTestResourceStatistic"
#userId = "" #Uncomment to use custom userId instead of user directory name

[[modelConfigs]]
contextLimit = 1_500
endpoint = "http://10.113.36.104"
modelType = "Comware-V1"
stopTokens = [ "<fim_pad>", "<|endoftext|>", "\n}" ]
suggestionCount = 1
temperature = 0.2

[modelConfigs.maxNewTokens]
function = 512
line = 48
snippet = 128

[modelConfigs.separateTokens]
end = "<fim_suffix>"
middle = "<fim_middle>"
start = "<fim_prefix>"

[[modelConfigs]]
contextLimit = 1_500
endpoint = "http://10.113.36.111"
modelType = "Comware-V2"
stopTokens = [ "<fim_pad>", "<|endoftext|>", "</s>", "\n}" ]
suggestionCount = 1
temperature = 0.2

[modelConfigs.maxNewTokens]
function = 512
line = 48
snippet = 128

[modelConfigs.separateTokens]
end = "_<SUF>"
middle = "_<MID>"
start = "_<PRE>"

[server]
host = "localhost"
port = 3_000
