currentModel = "CMW"

[[endpoints]]
endpoint = "http://10.113.36.104"
model = "CMW"

[[endpoints]]
endpoint = "http://10.113.36.111:9201"
model = "CODELLAMA"

[promptExtractor]
contextLimit = 1_500

[promptProcessor]
stopTokens = [ "<fim_pad>", "<|endoftext|>", "</s>", "\n}" ]
suggestionCount = 1
temperature = 0.2

  [promptProcessor.maxNewTokens]
  line = 60
  snippet = 512

  [[promptProcessor.separateTokens]]
  model = "CMW"
  end = "<fim_suffix>"
  middle = "<fim_middle>"
  start = "<fim_prefix>"

  [[promptProcessor.separateTokens]]
  model = "CODELLAMA"
  end = "▁<SUF>"
  middle = "▁<MID>"
  start = "▁<PRE>"

[server]
host = "localhost"
port = 3000
