authRequired = true
availableModels = [ "LS13B" ]
#Uncomment to use custom userId instead of user directory name
#userId = ""

[[endpoints]]
endpoint = "http://rdtest.h3c.com/kong/RdTestAiService/chatgpt"
model = "LS13B"

[promptExtractor]
contextLimit = 1_500

[promptProcessor]
stopTokens = [ "<fim_pad>", "<|endoftext|>", "</s>", "\n}" ]
suggestionCount = 1
temperature = 0.2

  [promptProcessor.maxNewTokens]
  line = 16
  snippet = 128

  [[promptProcessor.separateTokens]]
  model = "LS13B"
  end = ""
  middle = ""
  start = ""

[server]
host = "localhost"
port = 3000

[statistics]
endpoint = "http://10.153.227.40:10808"
